apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Need to install CRDs separate from Helm chart
# https://github.com/aws/eks-charts/tree/v0.0.226/stable/aws-load-balancer-controller#installing-the-chart
  - github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=v0.0.226
# - https://raw.githubusercontent.com/aws/eks-charts/refs/tags/v0.0.226/stable/aws-load-balancer-controller/crds/crds.yaml
# - https://raw.githubusercontent.com/aws/eks-charts/refs/tags/v0.0.226/stable/aws-load-balancer-controller/crds/gateway-crds.yaml

# For Gateway support
# https://kubernetes-sigs.github.io/aws-load-balancer-controller/v3.1/guide/gateway/gateway/
# https://aws.amazon.com/blogs/networking-and-content-delivery/aws-load-balancer-controller-adds-general-availability-support-for-kubernetes-gateway-api/
  - https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/refs/tags/v3.1.0/config/crd/gateway/gateway-crds.yaml
  - alb-gatewayclass.yaml


helmCharts:
  - name: aws-load-balancer-controller
    repo: https://aws.github.io/eks-charts
    version: 3.1.0
    releaseName: aws-loadbalancer
    namespace: loadbalancer
    valuesFile: values.yaml

