apiVersion: research.k8tre.io/v1alpha1
kind: Project
metadata:
  name: asthma
spec:
  description: "Asthma research project"
  apps:
    - name: jupyterhub
      type: jupyterhub
      url: "JUPYTERHUB_URL_PLACEHOLDER"
      config:
        workspace: "/asthma"
        quota: "2CPU"
    - name: guacamole
      type: vdi
      url: "GUACAMOLE_URL_PLACEHOLDER"
      config:
        protocol: rdp
        resolution: "1920x1080"
        desktop: "ubuntu-mate"
  profiles:
    - display_name: "Asthma Workspace 1"
      description: "A TRE workspace for federated analysis with Python"
      slug: "asthma-ws1"
      kubespawner_override:
        image: "ghcr.io/k8tre/marimo-notebook-workspace:latest"
        env:
          PROJECT_NAME: "asthma"
          WORKSPACE: "/asthma/ws1"
    - display_name: "Asthma MATE Desktop"
      description: "A Ubuntu MATE Desktop"
      slug: "asthma-desktop1"
      kubespawner_override:
        image: "ghcr.io/manics/jupyter-desktop-mate:latest"
        env:
          PROJECT_NAME: "asthma"
          WORKSPACE: "/asthma/ws1"

---
apiVersion: research.k8tre.io/v1alpha1
kind: Project
metadata:
  name: diabetes
spec:
  description: "Diabetes research project"
  apps:
    - name: jupyterhub
      type: jupyterhub
      url: "JUPYTERHUB_URL_PLACEHOLDER"
      config:
        workspace: "/diabetes"
        quota: "4CPU"
    - name: guacamole
      type: vdi
      url: "GUACAMOLE_URL_PLACEHOLDER"
      config:
        protocol: rdp
        resolution: "1920x1080"
        desktop: "ubuntu-mate"
  profiles:
    - display_name: "Diabetes Workspace 1"
      description: "Python data analysis for diabetes"
      slug: "diabetes-ws1"
      kubespawner_override:
        image: "docker.io/manics/k8tre-kerberos-sql-jupyterlab@sha256:9cda83ab29fac9684fa87a51573ce113ea69b1085fbfce221e80c3492f9a278b"
        env:
          PROJECT_NAME: "diabetes"
          WORKSPACE: "/diabetes/ws1"
---
apiVersion: research.k8tre.io/v1alpha1
kind: Project
metadata:
  name: hypertension
spec:
  description: "Hypertension research project"
  apps:
    - name: jupyterhub
      type: jupyterhub
      url: "JUPYTERHUB_URL_PLACEHOLDER"
      config:
        workspace: "/hypertension"
        quota: "2CPU"
    - name: guacamole
      type: vdi
      url: "https://guacamole.dev-k8tre.org"
      config:
        protocol: rdp
        resolution: "1920x1080"
        desktop: "ubuntu-mate"
  profiles:
    - display_name: "Hypertension Workspace 1"
      description: "A TRE workspace for federated analysis with Python"
      slug: "hypertension-ws1"
      kubespawner_override:
        image: "ghcr.io/k8tre/marimo-notebook-workspace:latest"
        env:
          PROJECT_NAME: "hypertension"
          WORKSPACE: "/hypertension/ws1"