prePuller:
  hook:
    enabled: false # Disable prePuller hook - see https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1621
hub:
  networkPolicy:
    egress:
      - ports:
          - port: 6443
          - port: 443
  config:
    Authenticator:
      enable_auth_state: true
    # Lookup URLs from
    # https://<keycloak-url>/realms/<realm>/.well-known/openid-configuration
    GenericOAuthenticator:
      client_id: jupyterhub
      client_secret: jupyterhub-client-secret
      # Accessed externally by the user
      oauth_callback_url: https://jupyter.dev.k8tre.internal/hub/oauth_callback
      authorize_url: https://keycloak.dev.k8tre.internal/realms/master/protocol/openid-connect/auth
      # Internal to the cluster: svc=keycloak ns=keycloak
      token_url: http://keycloak.keycloak/realms/master/protocol/openid-connect/token
      userdata_url: http://keycloak.keycloak/realms/master/protocol/openid-connect/userinfo
      scope:
        - openid
        # The custom scope name
        - k8tre-roles
      login_service: keycloak
      username_key: preferred_username
      userdata_params:
        state: state
      # The location of the custom Keycloak field in the userdata response
      auth_state_groups_key: oauth_user.k8tre.roles
      # JupyterHub defers to Keycloak for all group memberships
      manage_groups: true
      allowed_groups:
        # The Keycloak role for JupyterHub users
        - k8tre-users
      admin_groups:
        # The Keycloak role for JupyterHub admins
        - k8tre-admins
      # For CI testing only with self-signed certificates!
      validate_server_cert: false
    JupyterHub:
      authenticator_class: generic-oauth
proxy:
  service:
    type: ClusterIP
singleuser:
  cloudMetadata:
    # This requires elevated permissions which should be avoided. Use network policies instead.
    # See https://z2jh.jupyter.org/en/latest/administrator/security.html#audit-cloud-metadata-server-access
    blockWithIptables: false
  networkPolicy:
    enabled: false # These are managed by Cilium network policies
ingress:
  enabled: true
  hosts:
    - jupyter.k8tre-dev.trevolution.dev.hic.dundee.ac.uk
  ingressClassName: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jupyter.dev.k8tre.internal
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  tls:
    - hosts:
        - jupyter.k8tre-dev.trevolution.dev.hic.dundee.ac.uk
      secretName: jupyter-k8tre-tls

