apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cr8tor-publisher
    repo: https://lsc-sde.github.io/iac-helm-repository/
    version: 0.1.65
    releaseName: cr8tor
    namespace: cr8tor
    valuesFile: values.yaml

  - name: cr8tor-operator
    repo: oci://ghcr.io/karectl-crates/charts
    version: 0.1.0-beta.2
    releaseName: cr8tor-operator
    namespace: cr8tor
    valuesFile: operator-values.yaml

resources:
  - ../../base

patchesStrategicMerge:
  - ../../base/cr8tor-patch-disable-world.yaml
